### ISSUE TITLE
question: what is the goal of this?

### ISSUE THREAD

**Issue by foxsouns** [xyproto/zsnes#1]
are you working to improve upon zsnes, or just make it easy to compile on modern systems? what exactly is it that you want to do with this? saw this repo and my interest sparked for some odd reason. ive always liked zsnes's ui but hated how inaccurate it was..

**Comment by xyproto** [comment]
zsnes is unmaintained, does not compile and does not work on ie. 64-bit Arch Linux.

This repo makes it easy to compile and run zsnes on ie. 64-bit Arch Linux.

In addition to this, it is maintained, so if bugs are reported, I'll look into it.

**Comment by foxsouns** [comment]
> zsnes is unmaintained, does not compile and does not work on ie. 64-bit Arch Linux.
> 
> This repo makes it easy to compile and run zsnes on ie. 64-bit Arch Linux.
> 
> In addition to this, it is maintained, so if bugs are reported, I'll look into it.

zsnes is known widely for its inaccuracies: will you be trying to fix this, or are you just keeping it in an lts sort of fashion?

**Comment by xyproto** [comment]
Ah, got you. Just a type of LTS, but pull requests that fixes inaccuracies are welcome.
