### ISSUE TITLE
Support building on Ubuntu

### ISSUE THREAD

**Issue by jeffythedragonslayer** [xyproto/zsnes#15]
I have already installed `gcc-multilib`, `g++-multilib`, and `lib32z1-dev`, but I am still getting:

```
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libX11.so when searching for -lX11
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libX11.a when searching for -lX11
/usr/bin/ld: cannot find -lX11: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libX11.so when searching for -lX11
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libSDL.so when searching for -lSDL
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libSDL.a when searching for -lSDL
/usr/bin/ld: cannot find -lSDL: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libSDL.so when searching for -lSDL
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libpng16.so when searching for -lpng16
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libpng16.a when searching for -lpng16
/usr/bin/ld: cannot find -lpng16: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libpng16.so when searching for -lpng16
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libGL.so when searching for -lGL
/usr/bin/ld: cannot find -lGL: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libGL.so when searching for -lGL
collect2: error: ld returned 1 exit status
make: *** [Makefile:346: zsnes] Error 1
```

**Comment by xyproto** [comment]
Thanks for reporting!

**Comment by xyproto** [comment]
I tried installing Ubuntu in a Docker container, and got a bit further.

The main problem right now is that the equivalent of an `sdl12-compat` package does not seem to be available for Ubuntu, or I could not figure out how to install it. Perhaps the compat package needs to be installed for x86_64 and the SDL2 library needs to be installed for x86_64? This is hard to tell, and neither `apt` nor `dpkg` is particularly helpful in this regard.

Here is an approximate list of what I have tried so far, copied from the command line history.

It did not end up working! But I think I got a bit further:


---


Install various packages:

```sh
apt update
apt upgrade
dpkg --add-architecture i386
apt install git golang make nasm libsdl1.2-compat libsdl1.2-compat-dev zlib1g zlib1g-dev libpng-dev libpng16-16 build-essential libc6-dev-i386 g++-multilib libgl-dev ia32-libs-dev gcc-multilib lib32z1-dev file
```

Add a symlink to the x86 / i386 version of libpng:

```sh
ln -s /usr/lib/i386-linux-gnu/libpng16.so.16 libpng16.so
```

Add these to the Makefile, around line 86:

```make
CFLAGS += -I/usr/include/x86_64-linux-gnu -I /usr/include/X11
CXXFLAGS += -I/usr/include/x86_64-linux-gnu -I /usr/include/X11
LDFLAGS = -Wl,--as-needed -no-pie -L/usr/lib32 -L/usr/lib/i386-linux-gnu -Wl,--gc-sections -lz -lSDL12 -L. -lpng16 -lX11
```

Type `make` to see the compilation fail.

Try to install the x86 / i386 version of libpng:

```sh
apt install libpng16:i386 || apt install libpng16-16:i386
```

Try installing the Ubuntu equivalent of `sdl12-compat` for x86 / i386 and fail:

```sh
apt install libsdl1.2-compat libsdl1.2-compat-dev
apt install libsdl1.2-compat:i386 libsdl1.2-compat-dev:i386
apt install libsdl2-2.0-0:i386
apt install libsdl2-dev:i386
apt install libsdl2:i386
```

I wish something similar to `apt install libsdl12-compat:i386` would work, but it currently does not, in the Docker container that I tried it with. Suggestions are welcome.

**Comment by xyproto** [comment]
I am on Arch Linux. ZSNES has been tested on Arch and Fedora.

I want to make .deb for Debian/Ubuntu too, though.


Note to self: Debian sid has libsdl1.2-compat available, for different architectures:

https://packages.debian.org/sid/i386/libsdl1.2-compat/download

**Comment by xyproto** [comment]
I updated README.md to include notes about Ubuntu and Debian.
