### ISSUE TITLE
Add support for 8MB SA-1/SDD-1 roms

### ISSUE THREAD

**Issue by TrashRaccoonSnuffy** [xyproto/zsnes#17]
Currently, 8MB roms that utilize SA-1 or SDD-1 are not recognized by ZSNES and cannot be opened. There was a fork of the program that added support for these roms here https://fusoya.eludevisibility.org/emulator/zsnes8.html (source code linked on page as well) and if possible, the changes from it should be ported to here.

I could look into porting this feature to the repository, but I am unable to compile it on Ubuntu 20.04, so perhaps instructions should be added for it?

**Comment by xyproto** [comment]
Thanks for the feature request! I want to incorporate these improvements. But, looking at the fusoya web site, I could not see if the SA-1 changes are copyrighted or free to use and distribute. Furthermore, the author does not want to answer questions about this per e-mail:

> However, if for some reason you're just really determined to contact me anyway [...] and don't have an inquiry about source code or porting something I've worked on [...] ONLY then may you try emailing me

https://fusoya.eludevisibility.org/contact.html

Can you see if there is any license info, and/or e-mail the author at fusoyarelm@gmail.com and ask if the changes can be used here?

**Comment by xyproto** [comment]
Thanks for posting the reply.

I removed the e-mail address from my comment (even though I believe the spam bots are smart enough to add or remove words, and soon smart enough to follow any "unecryption" instructions tan average human could follow).

I guess finding out which changes should be made is the next step, and then testing if it works.

**Comment by TrashRaccoonSnuffy** [comment]
Solved with https://github.com/xyproto/zsnes/pull/23 , a solution will have to be found to not require 16MB maxromspace, but it shouldn't really affect anyone besides needing 10~ extra MB of RAM to run ZSNES. Fixing this just involves moving off the special end of ROM variables out of the rom buffer. I have no idea why it's designed this way, but it's an easy fix.
