### ISSUE TITLE
Hints to understand the code base

### ISSUE THREAD

**Issue by uddivert** [xyproto/zsnes#26]
Hello, I would like to help contribute to this project. Are there any tools to help becoming acquainted to this codebase?

**Comment by xyproto** [comment]
Hi! The code mainly consists of old C and 32-bit Assembly code, which are not well known for excellent readability. The main approach would be to know C and Assembly well and read through the source code. I don't know of any software that makes this much easier, unfortunately. There might be tools that can draw a call graph, but I'm not sure how helpful it would be. LLMs might also be helpful in explaining sections of the code or entire files, but at the time of writing, all of them are struggling quite a bit with both C and Assembly.
