### ISSUE TITLE
ZSNES Compiling Issues

### ISSUE THREAD

**Issue by P0W3** [xyproto/zsnes#8]
In the Command Prompt, I made a command, `make`, and it did not work.

What are the requirements for compiling ZSNES?

**Comment by xyproto** [comment]
Which OS are you on, and what is the error message?

The main goal is to support Linux on x86_64.

**Comment by P0W3** [comment]
Here is what I did.

![image](https://user-images.githubusercontent.com/18279115/210189005-2444ea50-cd79-452a-a921-9ef856519b0e.png)
![image](https://user-images.githubusercontent.com/18279115/210189008-a8c4f312-370d-4b47-9339-bfe86246ae79.png)

[Info.txt](https://github.com/xyproto/zsnes/files/10329764/Info.txt)

**Comment by xyproto** [comment]
Thanks for the screenshot.

Compiled executables for ZSNES 1.51 for Windows are available at https://sourceforge.net/projects/zsnes/files/zsnes/ZSNES%20v1.51/.

I can update the README.md file if it's not clear enough on what the project goals are and which platforms are currently supported.

Pull requests for making this repository build on Windows are welcome, but I personally think it will take more effort than it's worth.
